### ISSUE TITLE
make all 報錯？

### ISSUE THREAD

**Issue by ejmoog** [calcitem/chaosclock#10]
make: [Makefile:859: .depend] Error 1 (ignored)
make: *** No rule to make target 'evaluate.o', needed by 'chaosclock'.  Stop.

**Comment by calcitem** [comment]
Makefile暂未更新，删除多余文件。
现在工程是单文件，因此可以先用 `gcc -02 -g -o chaosclock chaosclock.cpp` 命令编译。
