### ISSUE TITLE
優化之後速度確實快，但出現問題

### ISSUE THREAD

**Issue by ejmoog** [calcitem/chaosclock#24]
用第五頁的局面：

9,10,8,1,4,7,11,6,5,3,12,2

當player1走完1之後，應該輪到p0，這裏出現兩個走法，其中4是落子，只能由player1才能落4。同時行動結束也沒有切換player。

可拿之前我的版本來作對比，我也看一下是哪裏的問題。

**Comment by ejmoog** [comment]
對的表現：

> select one option: 0
> movelist: 1  
> roll->value: 4 ; player: 0 ; lastmove: 1 ; maxdeep: 45
> ; board: 9, 10, 8, 0, 1, 7, 11, 6, 5, 3, 12, 2,  
> this_depth: 1 ; available move:2
>  0: ->value: 3 ; player: 1 ; lastmove: 2 ; maxdeep: 32
>  1: ->value: 1 ; player: 1 ; lastmove: 3 ; maxdeep: 45


 

錯的表現：

> select one option: 0
> Stage 2 took 143767 ms
> movelist: 1  
> roll->value: 4 ; player: 0 ; lastmove: 1 ; maxdeep: 45
> ; board: 9, 10, 8, 0, 1, 7, 11, 6, 5, 3, 12, 2,  
> this_depth: 1 ; available move:2
>  0: ->value: 4 ; player: 0 ; lastmove: 4 ; maxdeep: 36
>  1: ->value: 4 ; player: 0 ; lastmove: 2 ; maxdeep: 24

**Comment by calcitem** [comment]
建议记录问题时记录下对应的代码或链接。已经有150个提交了。如果对应的提交是一个较老的提交，这个提交之后的都不用排查了。

另外，我今天外出，可能得你那边先排一下。

**Comment by ejmoog** [comment]
> 建议记录问题时记录下对应的代码或链接。已经有150个提交了。如果对应的提交是一个较老的提交，这个提交之后的都不用排查了。
> 
> 另外，我今天外出，可能得你那边先排一下。

有問題的是最新的提交：[731b089](https://github.com/calcitem/chaosclock/commit/731b089309b01fd682fd8bffce292ab31745f975)

**Comment by calcitem** [comment]
那就是最新的代码了，可以用 git bitset 命令二分法排查。并且得小心新老版本 position 中 player 格式差异。

**Comment by calcitem** [comment]
刚回来。准备复现 Debug 此问题。

**Comment by ejmoog** [comment]
> 建议记录问题时记录下对应的代码或链接。已经有150个提交了。如果对应的提交是一个较老的提交，这个提交之后的都不用排查了。
> 
> 另外，我今天外出，可能得你那边先排一下。

有問題的是最新的提交：[731b089](https://github.com/calcitem/chaosclock/commit/731b089309b01fd682fd8bffce292ab31745f975)

> 刚回来。准备复现 Debug 此问题。

好的，感謝。

我還在考慮#22的問題，因為好像有點複雜。還想把「乙方在單數位的棋子」也考慮進去。

**Comment by calcitem** [comment]
是 "random_board 添加 static const" (c41965c21599255e6a9736720811c2abf2204a1e) 引入的，我没想明白为啥。

**Comment by ejmoog** [comment]
> 是 [8a00c04](https://github.com/calcitem/chaosclock/commit/8a00c04481e2a983d7cd09691778c58a81999949) 引入的，最后正确版本是 [13ee1b3](https://github.com/calcitem/chaosclock/commit/13ee1b3a400d3dada14798382c6baa593b9e546e)，我没想明白为啥。

個人猜測，內存池是提前先new開好空間，但是只開了100000個空間，結果就重覆了？

是否把100000調的足夠大？

**Comment by ejmoog** [comment]
據我個人理解，每個新開的new Position，到最後都有用，不能被銷毀。

**Comment by calcitem** [comment]
> > 是 [8a00c04](https://github.com/calcitem/chaosclock/commit/8a00c04481e2a983d7cd09691778c58a81999949) 引入的，最后正确版本是 [13ee1b3](https://github.com/calcitem/chaosclock/commit/13ee1b3a400d3dada14798382c6baa593b9e546e)，我没想明白为啥。
> 
> 個人猜測，內存池是提前先new開好空間，但是只開了100000個空間，結果就重覆了？
> 
> 是否把100000調的足夠大？

估计不是这个原因。

```c++
    Position *acquire()
    {
        if (m_pool.empty()) {
            return new Position();
        } else {
            auto obj = m_pool.back();
            m_pool.pop_back();
            return obj;
        }
    }
```

这里如果池中的不够，会调用 new 的。

**Comment by calcitem** [comment]
> 據我個人理解，每個新開的new Position，到最後都有用，不能被銷毀。

果然如此。原来的代码没有调用 delete，但是我加入了销毁动作。
不过，去掉销毁后，内存占用暴涨到 4G。

**Comment by calcitem** [comment]
对象池初始化时使用一次性分配内存再依次初始化的方式，而非一个一个对象地 new。

https://github.com/calcitem/chaosclock/commit/3f6be7b529ebf3d87f3789b18a4fbdfb454fde6d

如此修改后，耗时比解决这个本帖报告的 Bug 之前的版本还要快 20%。
