### ISSUE TITLE
什么情况下需要 sortChildren？

### ISSUE THREAD

**Issue by calcitem** [calcitem/chaosclock#5]
sortChildren這個函數似乎用處不大？所以现在先移除了。

之後把下面的幾個_children改成children。
 
這個是改變children滾的次序（以提高效率），但是假設我們是希望所有可能都走完的話，這個倒只是降低效率？

如后面优化之后，又需要排序了？

待查。

**Comment by ejmoog** [comment]
sortChildren排序是為第372行左右的代碼服務的：
```
            if ((pos->children[sa]->value == 1 &&
                 pos->children[sa]->player != pos->player) ||
                (pos->children[sa]->value == 4 &&
                 pos->children[sa]->player == pos->player)) {
                break;
            }
```
如果已經有一個child是己贏（4分），則不需要再算下去。就可以節省時間。

但是sortChildren有幾個問題，它佔用很多算力，如果沒有一個child是4分，則即使排序也沒用。

同時，如何排序也很難，通常都排不對。

所以，排序應該是沒有必要的。

以後如果能想到一種不佔太多時間也能弄出一個好的排序的方法（優先要走的棋都排在前面），則再加入。

**Comment by calcitem** [comment]
直棋当时是测试了十几种排序算法后选择了部分插入排序算法。后面也可以逐个算法试试找到最好的。STL的sort算法普适性强，但性能不高，中庸型。

**Comment by ejmoog** [comment]
看來如果我後面還要做其它弈棋AI的話，學習算法是必不可少的了。
