### ISSUE TITLE
Pieces 成员第一维改为使用数组会导致计算结果异常

### ISSUE THREAD

**Issue by calcitem** [calcitem/chaosclock#9]
struct Pieces 若如此修改：

```c++
struct Pieces
{
    vector<int8_t> stick[2] = {};
    vector<int8_t> hand[2] = {};
    vector<int8_t> running = {};
    vector<int8_t> stop[2] = {};
    vector<int8_t> stock[2] = {};
    vector<int8_t> dead[2] = {};
    vector<int8_t> free[2] = {};
};
```

然后将 `new_pieces.stop.size()` 改为 2.

这么修改能编译通过，但是运行结果有变化。

```
roll_sum:503459
max_depth:19
result_sum:679410

Stage 1 took 617 ms
board: 4, 3, 7, 11, 5, 10, 12, 0, 0, 2, 0, 0,
depth:0
player: 0
value:3
available move:6
  0: 2 (value: 4)
  1: 10 (value: 3)
  2: 11 (value: 4)
  3: 12 (value: 4)
  4: 6 (value: 4)
  5: 8 (value: 4)
Stage 2 took 0 ms
```

如能搞定，可以将 800ms 缩短为 617ms。

但是我不知道为啥这么改不行。

**Comment by calcitem** [comment]
乌龙，为 mod12 bug 造成。已修复。

**Comment by ejmoog** [comment]
在選擇行動時，需要對pieces的hand和running合併，這是當前棋手的可選行動。我不知道改成數組之後，能否正準獲取它們的長度，如果可以，就沒問題。

**Comment by calcitem** [comment]
如果不取长度可以吗？12+12一共24个字节，前面12是棋盘，后面12个是手中的棋子，依次遍历到底，手中没这个棋的，对应位置就是0。这样不用管手中有几个棋子。因为循环依次遍历，在数组长度不大的情况下，说不定比vector操作还节省计算量，并且也方便利用CPU Cache做prefetch。vector的话，计算期间分支跳转多，几做不了prefech。

**Comment by calcitem** [comment]
vector为啥操作开销大呢，是因为涉及内存分配，销毁，空间不够的情况下的再分配，还有数据的搬移等等，开销也不小，说不定还不如数组遍历快。

**Comment by calcitem** [comment]
Piece 内部有多个成员数组，和Piece内部成员不是数组，而是由多个Piece组成数组，哪种结构更好？

**Comment by ejmoog** [comment]
> Piece 内部有多个成员数组，和Piece内部成员不是数组，而是由多个Piece组成数组，哪种结构更好？

我不太明白，你能寫個示例出來嗎？

我感覺c++還提供了不少數據類型，這裏確實不宜用vector。因為「hand、stick、free、dead、stop、stock」這些都確定只有兩個int[6]，而vector是變長的。

但我不知道還有哪種數據類型可以用，我只知道vector能用…

**Comment by ejmoog** [comment]
> Piece 内部有多个成员数组，和Piece内部成员不是数组，而是由多个Piece组成数组，哪种结构更好？

我不太明白，你能寫個示例出來嗎？

我感覺c++還提供了不少數據類型，這裏確實不宜用vector。因為「hand、stick、free、dead、stop、stock」這些都確定只有兩個int[6]，而vector是變長的。

但我不知道還有哪種數據類型可以用，我只知道vector能用…

**Comment by ejmoog** [comment]
hand、stick、free、dead、stop、stock都應該做成二維int數組，一維長度是6，二維長度是2個。

run是一維數組，長度是12。

**Comment by ejmoog** [comment]
沒有值則是0。有值則是1~12。

**Comment by calcitem** [comment]
可以先优化成数组，OK后进一步优化为bit位运算。
